spring:
  cloud:
    openfeign:
      client:
        config:
          # 默认配置
          default:
            logger-level: full
            connect-timeout: 1000
            read-timeout: 2000
          # 具体 feign 客户端的超时配置
          service-product:
            logger-level: full
            # 连接超时，3000 毫秒
            connect-timeout: 3000
            # 读取超时，5000 毫秒
            read-timeout: 5000
            # 重试
#            retryer: feign.retryer.Default
            # 自定义请求拦截器
#          request-interceptors:
#            - top.coenocyte.order.interceptor.XTokenRequestInterceptor

feign:
  sentinel:
    enabled: true