#  ✅ 显式声明要加载的 Nacos 配置 配合 spring.profiles.active 使用、namespace
---

spring:
  config:
    import:
      - nacos:service-order.properties?group=DEFAULT_GROUP
    activate:
      on-profile: public # 只在public环境下加载
---

spring:
  config:
    import:
      - nacos:common.properties?group=order
      - nacos:database.properties?group=order
    activate:
      on-profile: 888eddc9-da98-4526-957c-e02da13e480d # 命名空间ID
---

spring:
  config:
    import:
      - nacos:common.properties?group=order
      - nacos:database.properties?group=order
    activate:
      on-profile: 5ba131e2-95eb-4ceb-9277-4e1849f62929 # 命名空间ID