server:
  port: 8000

spring:
  application:
    name: @application.name@
  profiles:
    active: 888eddc9-da98-4526-957c-e02da13e480d #      命名空间ID
    include: config, feign
  cloud:
    nacos:
#      discovery:
#        server-addr: 192.168.30.128:8848
#      config:
#        server-addr: 192.168.30.128:8848
      server-addr: 192.168.30.128:8848
#      discovery:
#        namespace: ${spring.profiles.active:public} # 服务发现命名空间，默认public
      config:
        import-check:
          enabled: false # 禁用配置中心的健康检查，没有明确指定配置文件的来源，防止启动时报错
        namespace: ${spring.profiles.active:public} # 默认public
#  config:
#    import: nacos:service-order.properties # 明确指定配置文件的来源，不会报错

    sentinel:
      transport:
        # 控制台地址
        dashboard: localhost:8080
      # 立即加载服务
      eager: true
      # 链路模式：相同资源下，仅对于某一 web 路径下的资源访问生效
      web-context-unify: false
logging:
  level:
    top.coenocyte.order.feign: debug


