server:
  port: 8000

spring:
  application:
    name: @application.name@
  profiles:
    active: 888eddc9-da98-4526-957c-e02da13e480d #      命名空间ID
  cloud:
    nacos:
#      discovery:
#        server-addr: 192.168.30.128:8848
#      config:
#        server-addr: 192.168.30.128:8848
      server-addr: 192.168.30.128:8848
      config:
        import-check:
          enabled: false # 禁用配置中心的健康检查，没有明确指定配置文件的来源，防止启动时报错
        namespace: ${spring.profiles.active:public} # 默认public
#  config:
#    import: nacos:service-order.properties # 明确指定配置文件的来源，不会报错

#  ✅ 显式声明要加载的 Nacos 配置 配合 spring.profiles.active 使用、namespace
---
spring:
  config:
    import:
      - nacos:service-order.properties?group=DEFAULT_GROUP

---
spring:
  config:
    import:
      - nacos:common.properties?group=order
      - nacos:database.properties?group=order
    activate:
      on-profile: 888eddc9-da98-4526-957c-e02da13e480d # 命名空间ID

---
spring:
  config:
    import:
      - nacos:common.properties?group=order
      - nacos:database.properties?group=order
    activate:
      on-profile: 5ba131e2-95eb-4ceb-9277-4e1849f62929 # 命名空间ID
