spring:
  application:
    name: seata-account
  datasource:
    url: jdbc:mysql://192.168.30.128:13306/spring_cloud_account_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      server-addr: 192.168.30.128:8848
      config:
        import-check:
          enabled: false
server:
  port: 20000

mybatis:
  mapper-locations: classpath:mapper/*.xml

#seata:
#  tx-service-group: default_tx_group #  seata的资源逻辑，可以按微服务的需要，在应用程序（客户端）对自行定义事务分组，每组取一个名字。
#  data-source-proxy-mode: XA
