server:
  port: 9000

spring:
  application:
    name: @application.name@
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.30.128:8848
#      config:
#        server-addr: 192.168.30.128:8848
#      禁用导入检查
      config:
        import-check:
          enabled: false
    sentinel:
      transport:
        # 控制台地址
        dashboard: localhost:8080
      # 立即加载服务
      eager: true
